// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA_MdMEMLqR8GL-SrkS-z-C7fd5FlPLls',
    appId: '1:651541504721:web:a9764986a592010a021bf0',
    messagingSenderId: '651541504721',
    projectId: 'authenticationapplicatio-58386',
    authDomain: 'authenticationapplicatio-58386.firebaseapp.com',
    storageBucket: 'authenticationapplicatio-58386.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3VuY67vfRotCDBdEfOdePCcGVVNsDZk',
    appId: '1:651541504721:android:0bbd3644018ae245021bf0',
    messagingSenderId: '651541504721',
    projectId: 'authenticationapplicatio-58386',
    storageBucket: 'authenticationapplicatio-58386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7joLBZKMyxgyr8_nd6ui4sZbmoAw1D7Y',
    appId: '1:651541504721:ios:28f5779c8a1a5181021bf0',
    messagingSenderId: '651541504721',
    projectId: 'authenticationapplicatio-58386',
    storageBucket: 'authenticationapplicatio-58386.firebasestorage.app',
    iosBundleId: 'com.example.triplens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7joLBZKMyxgyr8_nd6ui4sZbmoAw1D7Y',
    appId: '1:651541504721:ios:28f5779c8a1a5181021bf0',
    messagingSenderId: '651541504721',
    projectId: 'authenticationapplicatio-58386',
    storageBucket: 'authenticationapplicatio-58386.firebasestorage.app',
    iosBundleId: 'com.example.triplens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA_MdMEMLqR8GL-SrkS-z-C7fd5FlPLls',
    appId: '1:651541504721:web:a9b35c212ed195c4021bf0',
    messagingSenderId: '651541504721',
    projectId: 'authenticationapplicatio-58386',
    authDomain: 'authenticationapplicatio-58386.firebaseapp.com',
    storageBucket: 'authenticationapplicatio-58386.firebasestorage.app',
  );
}
